repos:

- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v16.0.6
  hooks:
  - id: clang-format
    types_or: [c++, c]

- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: v0.6.10
  hooks:
  - id: cmake-format

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
    exclude_types: [c++, c]
    exclude: (CMakeLists\.txt)|(.*\.cmake)
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
